### ISSUE TITLE
Routing to other websockify instances

### ISSUE THREAD

**Issue by samfrances** [novnc/websockify#273]
Apologies if this is not the place to post this question. If so, let me know and I'll delete and post in the appropriate forum.

I'm aware that the canonical use of websockify is to except a websocket connection and act as a bridge to a normal TCP socket connection.

However, I'm looking at a situation where I would like to use websockify's routing capabilities (meaning that websockify can't be on the same machine as the VNC server), but would also like use wss to encrypt right up to the machine hosting the VNC server (meaning that websockify has to be on the machine running the VNC server). 

Is there a way to that webockify can be used to route (I'm using a routing plugin that queries a database) to another websockify instance, which then performs the "websocket bridge" part of websockify's functionality?

**Comment by CendioOssman** [comment]
No, that is not possible as the only place in websockify that has a forwarding function is the websocket code. So you'd get multiple layers of the websocket protocol.

I suggest you have a look at a HTTP reverse proxy. Since websockets are HTTP, any properly implemented proxy should work. Search the novnc mailing list/group as well. I'm fairly sure this has been discussed before.

**Comment by samfrances** [comment]
Thanks for the information, @CendioOssman
