### ISSUE TITLE
To integrate websockify with existing C++ code!

### ISSUE THREAD

**Issue by gopal1022** [novnc/websockify#317]
I have to use WebSockets in my existing C++ code and I found that Websockify will do that for me.
I have searched a lot but unable to find the way to integrate the websockify into my project.
please help me out.

**Comment by CendioOssman** [comment]
It depends on what you need. We have a C implementation of the server side of a WebSocket in `other/websocket.c`, but nothing for implementing a client. Please have a look at `other/websockify.c` for how to use it.

Also note that the main focus here is the Python version, so the other languages might be a bit buggy or otherwise not up to date.
