### ISSUE TITLE
Websockify seems to be broken with the latest version of python (3.7.0-3)

### ISSUE THREAD

**Issue by saurabhg9** [novnc/websockify#359]
File "/usr/share/novnc/utils/websockify/websockify/websockifyserver.py", line 276, in do_GET
    SimpleHTTPRequestHandler.do_GET(self)
  File "/usr/lib/python3.7/http/server.py", line 650, in do_GET
    f = self.send_head()
  File "/usr/lib/python3.7/http/server.py", line 674, in send_head
    path = self.translate_path(self.path)
  File "/usr/lib/python3.7/http/server.py", line 820, in translate_path
    path = self.directory
AttributeError: 'ProxyRequestHandler' object has no attribute 'directory'

**Comment by 1Hyena** [comment]
I'm completely unable to use websockify's current latest version, as it always logs `Client closed connection`, failing to deliver anything. This may or may not be the same issue but fact is that the latest version from github is not working as expected at the moment. I am using `wstelnet.html` for testing and messages that I send from the browser will arrive at the TCP server over websockify, but whenever the server responds something back, webosckify messes something up and disconnects the parties.

**Comment by CendioOssman** [comment]
That must be something else as you would not be able to get the connection up at all with this bug.

**Comment by CendioOssman** [comment]
The bug here is probably a result of our multiple inheritence where we never call `SimpleHTTPRequestHandler.__init__()` properly. Might want to remake `WebSocketRequestHandler` in to a mixin instead.

**Comment by 1Hyena** [comment]
For the record, I tested with my own C++ implementation of a websocket proxy and it was able to successfully convert ws into plain tcp and keep the connection open. So from here we can deduce that the web browsers (firefox and chromium) did their part correctly and it must have been the websockify. Also, some older version of websockify works properly ( the one you could get with `apt-get install websockify` on ubuntu. The reason why I had to try the latest github version was because on manjaro arch linux websockify packages don't exist.

**Comment by CendioOssman** [comment]
Should be fixed in be5d30ad258f0d21c24b5dc51ad5de2912ecfc01. Thank you for reporting this.
