### ISSUE TITLE
No way to provide path to the server

### ISSUE THREAD

**Issue by piotrkochan** [novnc/websockify#417]
I have vnc server running on:
```
http://myvnc:4444/vpn/token_w8949ytfgsfgdfg
```

And all I can pass to websockify is `myvnc:4444/vpn` only. How can i pass `/vpn/token_w8949ytfgsfgdfg` path?

**Comment by piotrkochan** [comment]
similar question was here: #409

**Comment by salderma** [comment]
Hi all, I am interested in this topic as well, but I do not have a reference configuration to provide.  The OP of the linked issue was asked for nginx config and didn't reply so the issue was closed.

I am using Traefik to proxy to app containers.  Some of those app containers use novnc/websockify, and are user session specific.  One of the apps, orchestrates starting up an novnc container for each user, so I'm looking to see how I can bind the URL paths similarly to @piotrkochan.

**Comment by CendioOssman** [comment]
I'm afraid I don't understand what issue you are seeing. websockify generally doesn't care about the path. It will react to any WebSocket connection, no matter the path.

So please describe in more detail what you are doing and what errors you are seeing.

**Comment by samhed** [comment]
No response.
