### ISSUE TITLE
Can't connect to vnc server

### ISSUE THREAD

**Issue by frankbydefault** [novnc/websockify#481]
Currently trying to connect KasmVNC to noVNC client. For what i understand, websockify serves like a bridge beteween these two but everything that i tried it doesn't work. Being more specific, the server is running on port 8443 and it is initialized by `vncserver :10 -websocketPort 8443 -interface 0.0.0.0` , in the log files it says that everything is running but it appears at the last line `sh: 1: /home/franco/.vnc/xstartup: Permission denied` , i can't tell if is that the problem or not, since i can't create  websockify .log file with the command `--log-file=/tmp/websockify.log` , to discard it.

Following the websockify documentation `./run 6080 --wrap-mode=ignore -- vncserver -geometry 1024x768 :10` should be the command that connects the server to the client (port 6080) but i get an **Error code: 405** when trying to load the noVNC page and a **Warning: A VNC server is already running as :10**.

**Comment by samhed** [comment]
There seems to be two missunderstandings here.

Firstly, it seems your VNC server already has a websocket proxy built in, judging from the name of that option `websocketPort`? Are you sure you need to use websockify at all? I'd start by trying to use noVNC directly towards that VNC server of yours.

Secondly, when starting websockify like that you're starting a different vncserver. As described in the README where you found that command:

> Here is an example of using websockify to wrap the vncserver command (which backgrounds itself) for use with noVNC:
>
> `./run 5901 --wrap-mode=ignore -- vncserver -geometry 1024x768 :1`

If you've got a VNC server running already you need to specify where it's running. Try something like this instead:

`./run --web=<DIRECTORY_OF_NOVNC> 6080 <HOST_OF_VNC_SERVER>:<TCP_PORT_OF_VNC_SERVER>`

That should start websockify on port 6080, while proxying TCP data from your VNC server. Note that you probably have to start your VNC server differently in order to not use the built in websocket proxy.
